"""Serves the panel spec generated by scripts/extract-panels.py.

Loaded once at import. The spec is baked into the image, so a change means a rebuild —
the same trade quota_api makes with its monitoring_assets/.
"""
import json, pathlib

_PATH = pathlib.Path(__file__).parent / "panels.json"


def load() -> dict:
    if not _PATH.exists():
        return {"dashboards": [], "variables": [], "error": "panels.json missing from image"}
    return json.loads(_PATH.read_text())


SPEC = load()
