#!/usr/bin/env python3
"""Splice the Grafana dashboards into deploy/22-grafana.yaml as ConfigMaps.

22-grafana.yaml mounts one ConfigMap per dashboard, each marked `optional: true` so
Grafana still starts if one is missing. That makes a missing ConfigMap silent: every pod
reports Running and Grafana serves zero dashboards. Generating them from dashboards/*.json
keeps that JSON the single source of truth and keeps `kubectl apply -f deploy/`
self-sufficient.

Everything from the marker line to end of file is regenerated; the hand-written
Deployment, Service and provisioning ConfigMaps above it are left untouched.

test/test_deploy_manifests.py fails if the spliced region drifts from dashboards/.

Usage: gen-dashboard-configmaps.py <dashboard.json>... --into <manifest.yaml>
"""
import argparse, json, pathlib, yaml

MARKER = ("# --- generated by scripts/gen-dashboard-configmaps.py from dashboards/*.json ---\n"
          "# Do not edit below this line: edit the dashboard JSON and regenerate.\n")


def literal(dumper, data):
    """Emit multi-line strings as block scalars so the JSON stays readable in the manifest."""
    style = "|" if "\n" in data else None
    return dumper.represent_scalar("tag:yaml.org,2002:str", data, style=style)


class Dumper(yaml.SafeDumper):
    pass


Dumper.add_representer(str, literal)


def configmap(path):
    """One ConfigMap per dashboard, named as 22-grafana.yaml's volumes expect."""
    stem = path.stem
    # Reformatted rather than copied verbatim: a stable serialisation means the
    # drift test compares content, not incidental whitespace from an editor.
    body = json.dumps(json.loads(path.read_text()), indent=2, sort_keys=True) + "\n"
    return {
        "apiVersion": "v1",
        "kind": "ConfigMap",
        "metadata": {"name": f"grafana-dashboard-{stem}", "namespace": "gpu-monitoring"},
        "data": {f"{stem}.json": body},
    }


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("dashboards", nargs="+", type=pathlib.Path)
    ap.add_argument("--into", required=True, type=pathlib.Path,
                    help="manifest to splice into, below the generated marker")
    args = ap.parse_args()

    current = args.into.read_text()
    # Drop the previously generated region *and* the `---` that introduced it, or each
    # run leaves another separator behind. YAML tolerates the resulting empty document,
    # so the document count stays right while the file grows — hence the byte-level test.
    head = current.split(MARKER.splitlines()[0])[0].rstrip()
    if head.endswith("---"):
        head = head[:-3].rstrip()

    docs = [configmap(p) for p in sorted(args.dashboards)]
    body = yaml.dump_all(docs, Dumper=Dumper, sort_keys=False,
                         default_flow_style=False, width=10**6)
    args.into.write_text(f"{head}\n---\n{MARKER}{body}")
    print(f"spliced {len(docs)} ConfigMaps into {args.into}")


if __name__ == "__main__":
    main()
